# Generated by Django 3.1.2 on 2020-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20201030_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='speciality_job',
        ),
        migrations.AddField(
            model_name='staff',
            name='speciality',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
