# Generated by Django 3.1.2 on 2020-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(default='not to say', max_length=20),
        ),
    ]
