# Generated by Django 3.1.2 on 2020-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default='default', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Disease',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prescribtion',
            field=models.TextField(blank=True),
        ),
    ]
